- name: play level variables
  hosts: local
  connection: local
  vars: 
    COURSE: Ansible #equal to COURSE=ANSIBLE in shell, shell we refer $VAR or ${VAR}
    DURATION: 10HR
    TRAINER: Sreekanth Paleti
  tasks:
  - name: print course information
    ansible.builtin.debug:
    #vars refernce should be surrounded by ""
      msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is  {{ TRAINER }}"